/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projekt.frames;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import projekt.Refactor;
import projekt.helpers.Database;

/**
 *
 * @author anton
 */
public class ShowMeeting extends javax.swing.JFrame {

    private int id;

    /**
     * Creates new form ShowMeeting
     */
    public ShowMeeting(int id) {
        initComponents();

        fillValues(id);
        String query = "Select firstName, lastName from User JOIN Meeting_Attandence ON User.UserID = Meeting_Attandence.UserID WHERE MeetingID = " + id + "";
        try {
            fillTable(Database.fetchRows(query));
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    public void fillTable(ResultSet rs) {
        try {
            jTParticipants = new JTable(Refactor.tableModelBuilder(rs));

        } catch (SQLException e) {
            e.printStackTrace();
        }

        jspAttendingPeople.setViewportView(jTParticipants);
        jTParticipants.setVisible(true);
    }

    public void fillValues(int id) {

        try {
            String description = Database.fetchSingle("Select Description from Meeting where MeetingID = " + id + "");
            String time = Database.fetchSingle("Select Time from Meeting where MeetingID  =" + id + "");
            String organizerID = Database.fetchSingle("Select UserID from Meeting where MeetingID  =" + id + "");
            String firstName = Database.fetchSingle("Select firstName from User where UserID  =" + organizerID + "");
            String lastName = Database.fetchSingle("Select lastName from User where UserID  =" + organizerID + "");
            String date = Database.fetchSingle("Select Date from Meeting where MeetingID  =" + id + "");

            jTDescription.setText(description);
            jLTime.setText(time);
            jLFirstName.setText(firstName);
            jLLastName.setText(lastName);
            jLDate.setText(date);
            
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jspAttendingPeople = new javax.swing.JScrollPane();
        jTParticipants = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTDescription = new javax.swing.JTextArea();
        jLDescription = new javax.swing.JLabel();
        jLTime1 = new javax.swing.JLabel();
        jLTime = new javax.swing.JLabel();
        jLOrganizer = new javax.swing.JLabel();
        jLFirstName = new javax.swing.JLabel();
        jLLastName = new javax.swing.JLabel();
        jLDate1 = new javax.swing.JLabel();
        jLDate = new javax.swing.JLabel();
        jLAttending = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTParticipants.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jspAttendingPeople.setViewportView(jTParticipants);

        jTDescription.setColumns(20);
        jTDescription.setRows(5);
        jScrollPane2.setViewportView(jTDescription);

        jLDescription.setText("Mötesbeskrivning");

        jLTime1.setText("Tidpunkt:");

        jLTime.setText("jLabel3");

        jLOrganizer.setText("Anordnare:");

        jLFirstName.setText("jLabel5");

        jLLastName.setText("jLabel3");

        jLDate1.setText("Datum:");

        jLDate.setText("jLabel5");

        jLAttending.setText("Deltagare");

        jButton1.setText("Tillbaka");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jspAttendingPeople, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLOrganizer)
                                .addGap(22, 22, 22)
                                .addComponent(jLFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                .addGap(51, 51, 51))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLTime1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLTime, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLAttending, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLOrganizer)
                            .addComponent(jLFirstName)
                            .addComponent(jLLastName))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLTime1)
                            .addComponent(jLTime))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLDate1)
                            .addComponent(jLDate))))
                .addGap(18, 18, 18)
                .addComponent(jLAttending)
                .addGap(18, 18, 18)
                .addComponent(jspAttendingPeople, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLAttending;
    private javax.swing.JLabel jLDate;
    private javax.swing.JLabel jLDate1;
    private javax.swing.JLabel jLDescription;
    private javax.swing.JLabel jLFirstName;
    private javax.swing.JLabel jLLastName;
    private javax.swing.JLabel jLOrganizer;
    private javax.swing.JLabel jLTime;
    private javax.swing.JLabel jLTime1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTDescription;
    private javax.swing.JTable jTParticipants;
    private javax.swing.JScrollPane jspAttendingPeople;
    // End of variables declaration//GEN-END:variables
}
